version: 0.2
phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install zip
      - apt-get -y install git
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/CarFunction/CarFunction.csproj
      - dotnet restore test/CarFunction.Tests/CarFunction.Tests.csproj
      - dotnet test test/CarFunction.Tests/CarFunction.Tests.csproj
  build:
    commands:
      - echo Build started on `date`
      - cd src/CarFunction
      - dotnet lambda package-ci --output-template output-serverless.json
      - cd ../..
  post_build:
    commands:
      - echo Post build started on 'date'
      - cp src/CarFunction/output-serverless.json
artifacts:
  files:
    - output-serverless.json
