version: 0.2
phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install zip
      - apt-get -y install git
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/CarFunction/CarFunction.csproj
      - dotnet restore test/CarFunction.Tests/CarFunction.Tests.csproj
      - dotnet test test/CarFunction.Tests/CarFunction.Tests.csproj
  build:
    commands:
      - echo Build started on `date`
      - cd src/CarFunction
<<<<<<< HEAD
      - dotnet lambda package-ci --output-template output-serverless.json
=======
      - dotnet lambda package-ci -pl . -c Release -f netcoreapp2.0 -o ../../CarFunction-deploy.zip
>>>>>>> 8e55ba0b43a169806d5d41c7ba4168f27e58e83b
      - cd ../..
  post_build:
    commands:
      - echo Post build started on 'date'
      - cp src/CarFunction/output-serverless.json
artifacts:
  files:
    - output-serverless.json